owner-id = 0
owner-guild-ids = []
system-channel-id = 0
support-server-url = "https://discord.gg"

bot-token = ""
database-url = "asyncpg://postgres:youcannotpass@db:5432/square"

[colors]
theme = "#1FCEEC"
green = "#2ECC71"
red = "#E74C3C"
orange = "#E67E22"

[lavalink]
host = ""
port = 0
password = ""
region = ""
secure = false
